-- Student & Client Marketplace — migration v4
--
-- Run after migration_v3.sql. Additive: nothing is dropped, every existing
-- row keeps working exactly as before.
--
--   1. Teams        — students group up, invite each other, and submit together.
--   2. Deliverables — a lecturer or company sets the pieces of work themselves,
--                     instead of the four fixed phases.
--   3. Company KYC  — a company is verified before it can publish a brief.
--   4. Bookmarks    — save a brief, and a match score from skill overlap.

-- ------------------------------------------------------------------ 1. teams

CREATE TABLE IF NOT EXISTS teams (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    created_by  INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    project_id  INT REFERENCES projects(id) ON DELETE SET NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'forming'
                CHECK (status IN ('forming','applied','active','completed','disbanded')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS team_members (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id    INT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    user_id    INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role       VARCHAR(10) NOT NULL DEFAULT 'member'
               CHECK (role IN ('lead','member')),
    status     VARCHAR(10) NOT NULL DEFAULT 'invited'
               CHECK (status IN ('invited','active','declined','removed')),
    invited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    joined_at  TIMESTAMPTZ,
    UNIQUE (team_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_team_members_user ON team_members (user_id);
CREATE INDEX IF NOT EXISTS idx_team_members_open
    ON team_members (user_id) WHERE status = 'invited';

-- A team can apply for a brief, the same way a lone student does.
ALTER TABLE project_applications
    ADD COLUMN IF NOT EXISTS team_id INT REFERENCES teams(id) ON DELETE CASCADE;

-- Which team a placement belongs to, if any.
ALTER TABLE assignments
    ADD COLUMN IF NOT EXISTS team_id INT REFERENCES teams(id) ON DELETE SET NULL;

-- ------------------------------------------------- team submission confirming
--
-- One member prepares the submission; it does not leave the team until every
-- other active member has confirmed. A single rejection sends it back.

ALTER TABLE submissions
    ADD COLUMN IF NOT EXISTS team_id INT REFERENCES teams(id) ON DELETE SET NULL;
ALTER TABLE submissions
    ADD COLUMN IF NOT EXISTS created_by INT REFERENCES users(id) ON DELETE SET NULL;

-- 'awaiting_team' and 'changes_requested' are new stages for team work.
ALTER TABLE submissions DROP CONSTRAINT IF EXISTS submissions_stage_check;
ALTER TABLE submissions ADD CONSTRAINT submissions_stage_check
    CHECK (stage IN ('awaiting_team','changes_requested','with_lecturer',
                     'with_university','with_company','approved','revision'));

CREATE TABLE IF NOT EXISTS submission_confirmations (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id INT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    user_id       INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    decision      VARCHAR(10) NOT NULL DEFAULT 'pending'
                  CHECK (decision IN ('pending','confirmed','rejected')),
    comment       TEXT,
    decided_at    TIMESTAMPTZ,
    UNIQUE (submission_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_confirmations_submission
    ON submission_confirmations (submission_id);

-- ----------------------------------------------------------- 2. deliverables

CREATE TABLE IF NOT EXISTS deliverables (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   INT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    created_by   INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title        VARCHAR(200) NOT NULL,
    description  TEXT,
    due_date     DATE NOT NULL,
    position     INT NOT NULL DEFAULT 1,
    status       VARCHAR(20) NOT NULL DEFAULT 'draft'
                 CHECK (status IN ('draft','published','archived')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_deliverables_project ON deliverables (project_id);
CREATE INDEX IF NOT EXISTS idx_deliverables_live
    ON deliverables (project_id) WHERE status = 'published';

-- A submission may answer a named deliverable. NULL keeps the old behaviour,
-- where a submission is simply the next version of the whole project.
ALTER TABLE submissions
    ADD COLUMN IF NOT EXISTS deliverable_id INT REFERENCES deliverables(id) ON DELETE SET NULL;

-- ------------------------------------------------------------------- 3. KYC

ALTER TABLE companies
    ADD COLUMN IF NOT EXISTS verification_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (verification_status IN ('pending','verified','rejected'));
ALTER TABLE companies ADD COLUMN IF NOT EXISTS kyc_document_url VARCHAR(500);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS kyc_notes TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS kyc_submitted_at TIMESTAMPTZ;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS kyc_decided_at TIMESTAMPTZ;
ALTER TABLE companies
    ADD COLUMN IF NOT EXISTS kyc_decided_by INT REFERENCES users(id) ON DELETE SET NULL;

-- Companies that already exist were trusted before this rule, so keep them
-- trusted. Only new signups start at 'pending'.
UPDATE companies SET verification_status = 'verified', kyc_decided_at = NOW()
 WHERE verification_status = 'pending' AND created_at < NOW();

-- ------------------------------------------------ 4. bookmarks and matching

CREATE TABLE IF NOT EXISTS bookmarks (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    project_id INT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, project_id)
);

CREATE INDEX IF NOT EXISTS idx_bookmarks_user ON bookmarks (user_id);

-- What a student can do. Match scores compare this against project_skills.
CREATE TABLE IF NOT EXISTS student_skills (
    user_id  INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    skill_id INT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, skill_id)
);

CREATE INDEX IF NOT EXISTS idx_student_skills_skill ON student_skills (skill_id);
