-- Student & Client Marketplace — migration v3
--
-- Additive only. Run this in the Supabase SQL editor on top of schema.sql.
-- It drops nothing and keeps every existing row.
--
-- What it adds:
--   1. Independent students — people who sign up on the main page with no
--      university behind them.
--   2. Direct applications — an independent student asks a company for a
--      project themselves, with no lecturer in the middle.
--   3. Submission files — the actual project files, stored on disk, with a
--      full record of who sent what and when.
--   4. Project dates — published and completed timestamps.

-- ------------------------------------------------- 1. independent students

-- A placement no longer needs a lecturer. Independent students are supervised
-- by the company directly.
ALTER TABLE assignments ALTER COLUMN lecturer_id DROP NOT NULL;

-- Where the placement came from: a lecturer placed them, or they applied.
ALTER TABLE assignments
  ADD COLUMN IF NOT EXISTS source VARCHAR(20) NOT NULL DEFAULT 'lecturer'
  CHECK (source IN ('lecturer', 'direct'));

-- An independent student has student_profiles.university_id IS NULL.
-- Nothing to add — the column is already nullable.

-- ------------------------------------------------- 2. direct applications

CREATE TABLE IF NOT EXISTS project_applications (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  INT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    student_id  INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message     TEXT NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending','accepted','declined','withdrawn')),
    decided_at  TIMESTAMPTZ,
    decided_by  INT REFERENCES users(id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (project_id, student_id)
);

CREATE INDEX IF NOT EXISTS idx_applications_project
    ON project_applications (project_id);
CREATE INDEX IF NOT EXISTS idx_applications_open
    ON project_applications (project_id) WHERE status = 'pending';

-- ------------------------------------------------- 3. submission files

-- The work itself. The file lives on disk under UPLOAD_FOLDER; this table is
-- the record of it — who, what, how big, when, and a checksum so a tampered
-- or truncated file can be spotted.
CREATE TABLE IF NOT EXISTS submission_files (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id INT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    uploaded_by   INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    original_name VARCHAR(255) NOT NULL,
    stored_name   VARCHAR(255) NOT NULL,
    relative_path VARCHAR(500) NOT NULL,
    size_bytes    BIGINT NOT NULL,
    mime_type     VARCHAR(120),
    sha256        CHAR(64) NOT NULL,
    uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_submission_files_submission
    ON submission_files (submission_id);

-- Every download is recorded, so a company can prove it collected the work
-- and a student can see who took a copy.
CREATE TABLE IF NOT EXISTS file_downloads (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id      INT REFERENCES submission_files(id) ON DELETE CASCADE,
    submission_id INT REFERENCES submissions(id) ON DELETE CASCADE,
    user_id      INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind         VARCHAR(20) NOT NULL DEFAULT 'file'
                 CHECK (kind IN ('file','archive')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_file_downloads_submission
    ON file_downloads (submission_id);

-- The repository link is now optional — a student may upload files instead.
ALTER TABLE submissions ALTER COLUMN repo_url DROP NOT NULL;

-- ------------------------------------------------- 4. project dates

ALTER TABLE projects ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- Backfill so existing rows have sensible dates instead of nulls.
UPDATE projects SET published_at = created_at
 WHERE published_at IS NULL AND status IN ('open','engaged','completed');
UPDATE projects SET completed_at = created_at
 WHERE completed_at IS NULL AND status = 'completed';
