-- PraxoraX — migration v6
--
-- Run after migration_v5.sql. Additive.
--
--   1. A shareable portfolio link, so a student can hand an employer one URL
--      instead of a login.
--   2. A record of every consolidated certificate issued, so the number on a
--      printed page can be checked against something.

-- ------------------------------------------------------- 1. portfolio link

-- Random, unguessable, and revocable. NULL means the portfolio is private and
-- only the student can see it.
ALTER TABLE student_profiles
    ADD COLUMN IF NOT EXISTS portfolio_token VARCHAR(48) UNIQUE;
ALTER TABLE student_profiles
    ADD COLUMN IF NOT EXISTS portfolio_public BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE student_profiles
    ADD COLUMN IF NOT EXISTS headline VARCHAR(160);

-- ------------------------------------------- 2. consolidated certificates

-- The per-project certificates in `certificates` are unchanged. This is the
-- one covering a student's whole record at a point in time.
CREATE TABLE IF NOT EXISTS portfolio_certificates (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id    INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reference     VARCHAR(40) UNIQUE NOT NULL,
    project_count INT NOT NULL,
    -- A frozen copy of what the certificate said when it was issued, so a
    -- printed page can still be verified after the student finishes more work.
    snapshot      JSONB NOT NULL,
    issued_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_portfolio_certs_student
    ON portfolio_certificates (student_id, issued_at DESC);
